#DAFOS - CONFIGFILE
#TO KNOW EVERYTHING ABOUT THE YAML CONFIG OF DAFOS
#GO TO THIS WEBSITE : 51.51.51.51/dafos-api/
CONF-LEVEL-1:
    map-content:
    0101010010101010101010
	0101010010100101001101
	1010101010101010100101
	0101010100010100100101
	0101010101110010101101
	0101010100101010100111
    map:
	map-name: "LEVEL-1"
	map-debug: 0
        map-bg: "src/"
    teleporter:
     teleporter-nb: 2
    	tp-1:
      	coords: 9,9
      	tp-name: "tp1-LEVEL-2"
    	tp-2:  
      	coords: 9,8
      	tp-name: "tp2-LEVEL-2"
    mobs:
      mobs-nb: 2
      monster-1:
      	name: "Eythan Fellousi"
      	texture: "src/texture/mobs"
        life: 100
        damage: 5.0
        pm: 10
        pa: 6
        coords: 5,9
      monster-2:
      	name: "Youssef le bg"
      	texture: "src/texture/mobs"
        life: 113
        damage: 11.0
        pm: 43
        pa: 55
        coords: 1,9
    event:
      event-nb: 1
      items-1:
      	name: "COnfLevel1 de pd"
        texture: "src/texture/items"
        coords: 9,2
CONF-LEVEL-2: 
    map-content:
    0101010010101010101010
  0101010010100101001101
  1010101010101010100101
  0101010100010100100101
  0101010101110010101101
  0101010100101010100111
    map:
  map-name: "LEVEL-2"
  map-debug: 0
        map-bg: "src/"
    teleporter:
     teleporter-nb: 1
      tp-1:
        coords: 5,7
        tp-name: "LEVEL-3"
    mobs:
      mobs-nb: 2
      monster-1:
        name: "Encore"
        texture: "src/texture/mobs"
        life: 141
        damage: 5.0
        pm: 1041
        pa: 641
        coords: 5,9
      monster-2:
        name: "UN AUtre"
        texture: "src/texture/mobs"
        life: 11341
        damage: 141
        pm: 434
        pa: 55
        coords: 1,9
    event:
      event-nb: 1
      items-1:
        name: "Chest"
        texture: "src/texture/items"
        coords: 9,2
CONF-LEVEL-3:
    map-content:
    0101010010101010101010
  0101010010100101001101
  1010101010101010100101
  0101010100010100100101
  0101010101110010101101
  0101010100101010100111
    map:
  map-name: "LEVEL-3"
  map-debug: 0
        map-bg: "src/"
    teleporter:
     teleporter-nb: 1
      tp-1:
        coords: 1,9
        tp-name: "LEVEL-4"
    mobs:
      mobs-nb: 2
      monster-1:
        name: "ConfErAAE"
        texture: "src/texture/mobs"
        life: 4555
        damage: 541.0
        pm: 1041414
        pa: 6414
        coords: 1,2
      monster-2:
        name: "Fdpdera"
        texture: "src/texture/mobs"
        life: 1
        damage: 1
        pm: 4
        pa: 5
        coords: 3,4
    event:
      event-nb: 1
      items-1:
        name: "Chest"
        texture: "src/texture/items"
        coords: 10,2